[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "https://admin.yaasou.com/"
  to = "https://yaasou.herokuapp.com/ghost"
  status = 200
